name: nf-ont-call-variants

channels:
    - conda-forge
    - bioconda

dependencies:
    - python==3.11
    - pip
    - bioconda::bcftools
    - bioconda::bowtie2
    - bioconda::fastqc
    - bioconda::minimap2
    - bioconda::mosdepth
    - bioconda::samtools
    - conda-forge::gnuplot
    - conda-forge::openjdk
    - conda-forge::singularity
    - pip:
        - 'cutadapt>=4.0'
        - 'multiqc>=1.21'